import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import { AppBar, Toolbar, Container, Box, Button, Icon, Stack } from "@mui/material";
import Link from "@mui/material/Link";
import WavesIcon from '@mui/icons-material/Waves';

export default function Navigation() {
  const user = useUser();

  return (
    <>
      <Head>
        <title>Tide Share</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppBar position="fixed" sx={{ mb: 10 }}>
        <Toolbar>
          <Box>
            <Link href="/" color="inherit" underline="none">
              <Stack direction="row-reverse" >
                <Box sx={{ fontSize: "3ex", ml: 1 }}>TIDESHARE</Box>
                <WavesIcon />
              </Stack>
            </Link>
          </Box>
          <Container sx={{ ml: 3, justifyContent: "center", alignItems: "center" }}>
            <Link
              underline="none"
              color="inherit"
              href="./AboutUs"
              fontSize="inherit"
              sx={{ justifyContent: "center" }}
            >
              ABOUT US
            </Link>

            {!!user.isSignedIn && (
              <Link
                underline="none"
                color="inherit"
                href="./YourPosts"
                fontSize="inherit"
                sx={{
                  ml: 3,
                }}
              >
                YOUR POSTS
              </Link>
            )}
          </Container>
          <Box>
            <Link underline="none" href="#" color="inherit">
              {!user.isSignedIn && (
                <SignInButton>
                  <Button color="inherit" variant="text">
                    Sign in
                  </Button>
                </SignInButton>
              )}
              {!!user.isSignedIn && (
                <SignOutButton>
                  <Button color="inherit" variant="text">
                    Logout
                  </Button>
                </SignOutButton>
              )}
            </Link>
          </Box>
        </Toolbar>
      </AppBar>
    </>
  );
}
